trigger:
  branches:
    include:
      - master

pool:
  name: Default
  demands:
  - agent.name -equals vikas

steps:
- script: |
    python --version
    python main.py
  displayName: 'Print Message'
