trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- script: |
    "C:\\Users\\Coditas\\AppData\\Local\\Programs\\Python\\Python310\\python.exe" main.py
    echo "hi"
  displayName: 'Print Message'
